defmodule Amanogawa.Atlas.EventQueries do
  @moduledoc """
  The critical query of the project (ADR 0007): events in a viewport and a
  time window, ranked by importance, server-limited. Every PostGIS fragment
  for `Amanogawa.Atlas.Event` lives here (`.claude/rules/geo-temporal.md`):
  no other module builds a spatial or temporal `where` clause on events.

  ## Filters

    * spatial: `ST_Intersects(geom, ST_MakeEnvelope(...))`, `OR`-ed across
      one or two envelopes (two when the requested bbox crosses the
      antimeridian, see `AmanogawaWeb.Params.EventsQuery.parse_bbox/1`).
    * temporal: interval overlap on years only (`.claude/rules/
      geo-temporal.md`: sub-year comparison is out of scope for this
      query), `begin_year <= to AND coalesce(end_year, begin_year) >= from`.
    * geometry required: an event without `geom` cannot be placed on the
      map and is excluded.

  Ranked by `sitelink_count` descending, tie-broken by `qid` ascending for
  a deterministic order across identical-importance events (otherwise
  PostgreSQL is free to return ties in any order, which would make `LIMIT`
  page boundaries and test assertions flaky).

  ## Query plan (issue #014)

  Measured with `EXPLAIN (ANALYZE, BUFFERS)` against a synthetic corpus of
  420,000 `atlas.events` rows: coordinates uniform over the whole globe (no
  clustering to help a bbox filter), `begin_year` uniform over
  [-3000, 2026], `sitelink_count` right-skewed (`floor(random()^5 * 5000)`,
  matching the real Wikidata shape where a small share of events dominates
  the ranking), and 10% of rows with no geometry (matching real ingestion,
  where location resolution sometimes fails). Generated by a throwaway SQL
  seed script kept outside the repository, never checked in, since the
  real ~420,000-row corpus (#010) has not been imported in this
  environment.

  Three scenarios, each `VACUUM ANALYZE`d first and run several times to
  confirm a stable plan:

    1. World bbox, full time range (`bbox` and `from`/`to` both absent):
       43 ms planning, 67-71 ms execution (~110-115 ms total).
    2. Continental bbox (~14M km^2, `-10,35,40,70`), wide window
       (`-3000..2026`): under 1 ms planning, 62-66 ms execution.
    3. Zoomed bbox (~550 km across, `0,45,5,50`), narrow window
       (`1700..2026`, 13 matching rows): under 1 ms planning, under 1 ms
       execution.

  All three stay far under the 300 ms budget. A fourth, deliberately
  adversarial scenario was also measured: world bbox (no spatial
  narrowing at all) crossed with a 10-year window landing on ordinary
  (non-important) events, forcing the planner to walk far down the
  importance-ordered index before collecting `LIMIT` matches. Even there:
  43 ms planning, 168 ms execution, ~210 ms total, still inside budget.

  Note on planning time: the ~43 ms figure above comes from `EXPLAIN` with
  literal coordinates inlined in the SQL text, which forces a full
  parse/plan on every run. Ecto/Postgrex issue this query as a
  parameterized prepared statement and cache it per connection, so
  production planning cost after the first execution on a given connection
  is expected to be a small fraction of this worst case.

  Indexes kept (`priv/repo/migrations/20260723140000_add_events_query_indexes.exs`):

    * NEW: `atlas.events(sitelink_count DESC, qid) WHERE geom IS NOT NULL`
      (`events_sitelink_count_qid_partial_index`), a partial btree matching
      this query's `ORDER BY` and its `WHERE geom IS NOT NULL` filter
      exactly. The planner walks it in output order and stops at `LIMIT`
      without a separate sort step: measured as the plan of choice for
      scenario 1 and the adversarial scenario above, where no bbox
      narrows the scan. Before this index existed, scenario 1 paid for an
      `Incremental Sort` on top of the pre-existing plain `sitelink_count`
      index (still faster than a full scan, but with a real sort cost and
      no `geom IS NOT NULL` narrowing); the partial index removes both.
    * the existing GiST index on `geom` (`create_atlas_events` migration)
      is the planner's choice for scenarios 2 and 3: a selective bbox
      makes a GiST bitmap scan (+ recheck) cheaper than walking the
      importance order, then the much smaller matching set is sorted in
      memory.
    * the existing plain btree on `begin_year` (`create_atlas_events`
      migration) is chosen by the planner (as a `BitmapAnd` with the GiST
      index) for the mirror case of scenario 3: a moderately selective bbox
      combined with a very narrow year window, where filtering by year
      first is cheaper than either index alone. Measured directly (not
      one of the three required scenarios, but real: continental bbox,
      10-year window): 43 ms planning, 68 ms execution.

  A composite `(begin_year, sitelink_count DESC)` btree was benchmarked
  and discarded: created and measured against the same adversarial
  scenario it targets (world bbox, narrow year window), the planner never
  chose it, keeping the partial `sitelink_count` index instead (168 ms vs.
  an estimated cost an order of magnitude higher for the composite path).
  A range filter on `begin_year` cannot use a trailing `sitelink_count`
  key for a global sort, only within one exact `begin_year` value, so it
  cannot serve this query's "importance order across a year range" shape.
  It also adds write overhead on every ingestion upsert without a measured
  read benefit, so it was dropped rather than migrated.

  Lesson for future composite index decisions on this table: a composite
  index only pays off when its leading column is filtered by equality (or
  is the sort key itself); a *range* filter on the leading column defeats
  ordering by a trailing column, no matter how selective that range looks
  on paper. Confirm the choice by disabling the candidate indexes and
  comparing `EXPLAIN (ANALYZE, BUFFERS)` plans directly (a `BEGIN`/`DROP
  INDEX`/`ROLLBACK` cycle keeps this test non-destructive) rather than by
  the planner's cost estimate alone.
  """

  import Ecto.Query

  alias Amanogawa.Atlas.Event
  alias Amanogawa.Atlas.EventLink
  alias Amanogawa.Atlas.TimeScale
  alias Amanogawa.Repo

  @type envelope :: %{min_lon: float(), min_lat: float(), max_lon: float(), max_lat: float()}
  @type opts :: %{
          envelopes: [envelope(), ...],
          from: integer(),
          to: integer(),
          limit: pos_integer()
        }
  @type row :: %{
          qid: String.t(),
          label: String.t() | nil,
          year: integer(),
          precision: integer(),
          importance: integer(),
          geom: Geo.Point.t()
        }
  @type link_row :: %{
          type: EventLink.link_type(),
          direction: :outgoing | :incoming,
          target_qid: String.t(),
          target_label: String.t() | nil,
          target_year: integer(),
          target_geom: Geo.Point.t()
        }

  @doc """
  Lists events intersecting `opts.envelopes`, overlapping the
  `[opts.from, opts.to]` year window, ranked by importance, limited to
  `opts.limit` rows. Events without a geometry are excluded.

  Returns the minimal projection needed to build a GeoJSON feature: `qid`,
  a French-with-English-fallback `label`, `year`/`precision` (the begin
  date only: the map shows a punctual marker), `importance`, and `geom`.
  """
  @spec list_events(opts()) :: [row()]
  def list_events(%{envelopes: envelopes, from: from, to: to, limit: limit}) do
    Event
    |> where([e], not is_nil(e.geom))
    |> where(^bbox_condition(envelopes))
    |> where([e], e.begin_year <= ^to and coalesce(e.end_year, e.begin_year) >= ^from)
    |> order_by([e], desc: e.sitelink_count, asc: e.qid)
    |> limit(^limit)
    |> select([e], %{
      qid: e.qid,
      label: coalesce(e.label_fr, e.label_en),
      year: e.begin_year,
      precision: e.begin_precision,
      importance: e.sitelink_count,
      geom: e.geom
    })
    |> Repo.all()
  end

  # Server-side cap on the number of relations returned per direction
  # (issue security-review #5): `list_links/1` has no client-controlled
  # limit param (unlike `list_events/1`), so a highly connected event could
  # otherwise return an unbounded number of `LineString` features. 200 per
  # direction (400 total, worst case) comfortably covers every real event
  # in the corpus while keeping the response bounded
  # (`.claude/rules/security.md`: every user-controlled input is bounded
  # server-side; here the input is the *event itself*, whose in-degree/
  # out-degree is not something ingestion caps upstream).
  @links_limit_per_direction 200

  @doc """
  Lists the typed relations of the event identified by `event_id` (issue
  #017): one row per relation where `event_id` is either the source or the
  target, `direction` telling which. Only relations whose *other* endpoint
  has a geometry are returned: an event without `geom` cannot anchor a
  line, so it is excluded there rather than surfacing a feature that
  cannot be drawn. The `event_id` side's own geometry is the caller's
  concern (`Amanogawa.Atlas.list_event_links_geojson/1`), not filtered
  here.

  Each direction is independently capped at #{@links_limit_per_direction}
  rows (see `@links_limit_per_direction`), ranked by the *other* endpoint's
  `sitelink_count` descending, tied by `qid` ascending for a deterministic
  order (mirrors `list_events/1`'s own ranking/tie-break, so a highly
  connected event's relations are truncated to its most important ones,
  not an arbitrary database-order slice).
  """
  @spec list_links(Ecto.UUID.t()) :: [link_row()]
  def list_links(event_id) do
    outgoing =
      event_id
      |> outgoing_links_query()
      |> Repo.all()
      |> Enum.map(&Map.put(&1, :direction, :outgoing))

    incoming =
      event_id
      |> incoming_links_query()
      |> Repo.all()
      |> Enum.map(&Map.put(&1, :direction, :incoming))

    outgoing ++ incoming
  end

  @type histogram_opts :: %{
          from: integer(),
          to: integer(),
          buckets: pos_integer(),
          scale: TimeScale.t()
        }

  @doc """
  Counts events whose `begin_year` falls in `[opts.from, opts.to]`, grouped
  by their position on `opts.scale`'s symlog axis (issue #020): one SQL
  `width_bucket` aggregation, no per-event Elixir loop.

  Returns a sparse map `%{bucket_index => count}`, `bucket_index` 1-based
  (PostgreSQL's `width_bucket` convention). `Amanogawa.Atlas.event_histogram/1`
  turns this into the dense, zero-filled response the API contract
  promises.

  `opts.scale`'s `pivot` and `max_year` are passed as bound query
  parameters into the `width_bucket` fragment below, never duplicated as
  literals in the SQL text (`.claude/rules/geo-temporal.md`: the symlog
  formula lives in exactly one place, `Amanogawa.Atlas.TimeScale`'s
  moduledoc; this fragment computes the *same* `t(year)` formula, just
  inline in SQL since a set-based aggregation cannot call back into
  Elixir per row). `low`/`high` (the bucket boundaries in position space)
  are `TimeScale.position/2` computed in Elixir from `opts.from`/`opts.to`
  and passed as parameters too, so PostgreSQL never needs its own copy of
  the `ln`-based position formula beyond the one `t(year)` fragment.

  An event landing exactly on `opts.to` (`begin_year == opts.to`) is
  assigned to the *last* bucket, not PostgreSQL's default "count + 1"
  overflow bucket for an operand `>= high`: the result is clamped into
  `[1, opts.buckets]` (`least(greatest(..., 1), buckets)`), so the last
  bucket is closed on both ends while every other bucket boundary stays
  half-open (`[low, high)`, `width_bucket`'s own semantics). The same
  clamp absorbs the sub-ULP floating-point disagreement that can occur
  between PostgreSQL's `ln` and Elixir's `:math.log` for an operand
  mathematically equal to a boundary (verified against real data by the
  `Amanogawa.Atlas.EventQueriesTest` DataCase test comparing this
  fragment's bucket assignment to `TimeScale.position/2`'s).
  """
  @spec histogram_counts(histogram_opts()) :: %{pos_integer() => non_neg_integer()}
  def histogram_counts(%{from: from, to: to, buckets: buckets, scale: scale}) do
    low = TimeScale.position(scale, from)
    high = TimeScale.position(scale, to)

    # Built as a map of per-field `dynamic/2` expressions, interpolated as
    # a whole (`^selects`) rather than pinning the `bucket` fragment alone
    # inside a literal select map: Ecto only allows a dynamic to appear as
    # the *entire* select value (`select: ^fields`), not nested inside one
    # (`select: %{field: ^dynamic(...)}`), per `Ecto.Query`'s "Dynamic
    # queries" documentation.
    selects = %{
      bucket: histogram_bucket_expr(scale, low, high, buckets),
      count: dynamic([e], count(e.id))
    }

    # `begin_year` is required at the `Amanogawa.Atlas.Event` changeset
    # boundary (`.claude/rules/elixir-idioms.md`: no defensive nil-check on
    # data already validated past that boundary), unlike `geom`
    # (`list_events/1` above), which is genuinely optional.
    Event
    |> where([e], e.begin_year >= ^from and e.begin_year <= ^to)
    |> select(^selects)
    |> group_by([e], selected_as(:bucket))
    |> Repo.all()
    |> Map.new(fn %{bucket: bucket, count: count} -> {bucket, count} end)
  end

  # `t(min_year)` (see `Amanogawa.Atlas.TimeScale`'s moduledoc) is constant
  # for a given scale, computed once in Elixir with the exact same formula
  # `Amanogawa.Atlas.TimeScale.position/2` uses, and passed as a single
  # bound parameter below rather than recomputed per row in SQL.
  defp symlog_t_min(%TimeScale{min_year: min_year, max_year: max_year, pivot: pivot}) do
    :math.log(1 + (max_year - min_year) / pivot)
  end

  # The `width_bucket` expression shared by `select` (aliased `:bucket` via
  # `selected_as/2`) and `group_by` (referencing that alias via
  # `selected_as/1`) in `histogram_counts/1` above: PostgreSQL requires
  # grouping by the same expression a computed `select` column comes from,
  # and `selected_as/1` is what lets `group_by` reference the alias instead
  # of repeating the SQL text a second time. `begin_year` is bound inside
  # the fragment string (Ecto interpolates `e.begin_year` positionally,
  # like every other fragment in this module), everything else
  # (`max_year`, `pivot`, `t_min`, `low`, `high`, `buckets`) is a query
  # parameter from `scale` and the caller's window, never a literal.
  defp histogram_bucket_expr(
         %TimeScale{max_year: max_year, pivot: pivot} = scale,
         low,
         high,
         buckets
       ) do
    t_min = symlog_t_min(scale)

    dynamic(
      [e],
      selected_as(
        fragment(
          "least(greatest(width_bucket(1 - ln(1 + (?::float - ?) / ?) / ?, ?, ?, ?), 1), ?)",
          ^max_year,
          e.begin_year,
          ^pivot,
          ^t_min,
          ^low,
          ^high,
          ^buckets,
          ^buckets
        ),
        :bucket
      )
    )
  end

  defp outgoing_links_query(event_id) do
    EventLink
    |> where([l], l.source_id == ^event_id)
    |> join(:inner, [l], t in Event, on: l.target_id == t.id)
    |> where([_l, t], not is_nil(t.geom))
    |> order_by([_l, t], desc: t.sitelink_count, asc: t.qid)
    |> limit(^@links_limit_per_direction)
    |> select([l, t], %{
      type: l.type,
      target_qid: t.qid,
      target_label: coalesce(t.label_fr, t.label_en),
      target_year: t.begin_year,
      target_geom: t.geom
    })
  end

  defp incoming_links_query(event_id) do
    EventLink
    |> where([l], l.target_id == ^event_id)
    |> join(:inner, [l], s in Event, on: l.source_id == s.id)
    |> where([_l, s], not is_nil(s.geom))
    |> order_by([_l, s], desc: s.sitelink_count, asc: s.qid)
    |> limit(^@links_limit_per_direction)
    |> select([l, s], %{
      type: l.type,
      target_qid: s.qid,
      target_label: coalesce(s.label_fr, s.label_en),
      target_year: s.begin_year,
      target_geom: s.geom
    })
  end

  defp bbox_condition(envelopes) do
    Enum.reduce(envelopes, dynamic(false), fn envelope, acc ->
      dynamic(
        [e],
        ^acc or
          fragment(
            "ST_Intersects(?, ST_MakeEnvelope(?, ?, ?, ?, 4326))",
            e.geom,
            ^envelope.min_lon,
            ^envelope.min_lat,
            ^envelope.max_lon,
            ^envelope.max_lat
          )
      )
    end)
  end
end
