defmodule Amanogawa.Atlas.EventQueries do
  @moduledoc """
  The critical query of the project (ADR 0007): events in a viewport and a
  time window, ranked by importance, server-limited. Every PostGIS fragment
  for `Amanogawa.Atlas.Event` lives here (`.claude/rules/geo-temporal.md`):
  no other module builds a spatial or temporal `where` clause on events.

  ## Filters

    * spatial: `ST_Intersects(geom, ST_MakeEnvelope(...))`, `OR`-ed across
      one or two envelopes (two when the requested bbox crosses the
      antimeridian, see `AmanogawaWeb.Params.EventsQuery.parse_bbox/1`).
    * temporal: interval overlap on years only (`.claude/rules/
      geo-temporal.md`: sub-year comparison is out of scope for this
      query), `begin_year <= to AND coalesce(end_year, begin_year) >= from`.
    * geometry required: an event without `geom` cannot be placed on the
      map and is excluded.

  Ranked by `sitelink_count` descending, tie-broken by `qid` ascending for
  a deterministic order across identical-importance events (otherwise
  PostgreSQL is free to return ties in any order, which would make `LIMIT`
  page boundaries and test assertions flaky).

  ## Query plan (issue #014)

  Measured with `EXPLAIN (ANALYZE, BUFFERS)` against a synthetic corpus of
  420,000 `atlas.events` rows: coordinates uniform over the whole globe (no
  clustering to help a bbox filter), `begin_year` uniform over
  [-3000, 2026], `sitelink_count` right-skewed (`floor(random()^5 * 5000)`,
  matching the real Wikidata shape where a small share of events dominates
  the ranking), and 10% of rows with no geometry (matching real ingestion,
  where location resolution sometimes fails). Generated by a throwaway SQL
  seed script kept outside the repository, never checked in, since the
  real ~420,000-row corpus (#010) has not been imported in this
  environment.

  Three scenarios, each `VACUUM ANALYZE`d first and run several times to
  confirm a stable plan:

    1. World bbox, full time range (`bbox` and `from`/`to` both absent):
       43 ms planning, 67-71 ms execution (~110-115 ms total).
    2. Continental bbox (~14M km^2, `-10,35,40,70`), wide window
       (`-3000..2026`): under 1 ms planning, 62-66 ms execution.
    3. Zoomed bbox (~550 km across, `0,45,5,50`), narrow window
       (`1700..2026`, 13 matching rows): under 1 ms planning, under 1 ms
       execution.

  All three stay far under the 300 ms budget. A fourth, deliberately
  adversarial scenario was also measured: world bbox (no spatial
  narrowing at all) crossed with a 10-year window landing on ordinary
  (non-important) events, forcing the planner to walk far down the
  importance-ordered index before collecting `LIMIT` matches. Even there:
  43 ms planning, 168 ms execution, ~210 ms total, still inside budget.

  Note on planning time: the ~43 ms figure above comes from `EXPLAIN` with
  literal coordinates inlined in the SQL text, which forces a full
  parse/plan on every run. Ecto/Postgrex issue this query as a
  parameterized prepared statement and cache it per connection, so
  production planning cost after the first execution on a given connection
  is expected to be a small fraction of this worst case.

  Indexes kept (`priv/repo/migrations/20260723140000_add_events_query_indexes.exs`):

    * NEW: `atlas.events(sitelink_count DESC, qid) WHERE geom IS NOT NULL`
      (`events_sitelink_count_qid_partial_index`), a partial btree matching
      this query's `ORDER BY` and its `WHERE geom IS NOT NULL` filter
      exactly. The planner walks it in output order and stops at `LIMIT`
      without a separate sort step: measured as the plan of choice for
      scenario 1 and the adversarial scenario above, where no bbox
      narrows the scan. Before this index existed, scenario 1 paid for an
      `Incremental Sort` on top of the pre-existing plain `sitelink_count`
      index (still faster than a full scan, but with a real sort cost and
      no `geom IS NOT NULL` narrowing); the partial index removes both.
    * the existing GiST index on `geom` (`create_atlas_events` migration)
      is the planner's choice for scenarios 2 and 3: a selective bbox
      makes a GiST bitmap scan (+ recheck) cheaper than walking the
      importance order, then the much smaller matching set is sorted in
      memory.
    * the existing plain btree on `begin_year` (`create_atlas_events`
      migration) is chosen by the planner (as a `BitmapAnd` with the GiST
      index) for the mirror case of scenario 3: a moderately selective bbox
      combined with a very narrow year window, where filtering by year
      first is cheaper than either index alone. Measured directly (not
      one of the three required scenarios, but real: continental bbox,
      10-year window): 43 ms planning, 68 ms execution.

  A composite `(begin_year, sitelink_count DESC)` btree was benchmarked
  and discarded: created and measured against the same adversarial
  scenario it targets (world bbox, narrow year window), the planner never
  chose it, keeping the partial `sitelink_count` index instead (168 ms vs.
  an estimated cost an order of magnitude higher for the composite path).
  A range filter on `begin_year` cannot use a trailing `sitelink_count`
  key for a global sort, only within one exact `begin_year` value, so it
  cannot serve this query's "importance order across a year range" shape.
  It also adds write overhead on every ingestion upsert without a measured
  read benefit, so it was dropped rather than migrated.

  Lesson for future composite index decisions on this table: a composite
  index only pays off when its leading column is filtered by equality (or
  is the sort key itself); a *range* filter on the leading column defeats
  ordering by a trailing column, no matter how selective that range looks
  on paper. Confirm the choice by disabling the candidate indexes and
  comparing `EXPLAIN (ANALYZE, BUFFERS)` plans directly (a `BEGIN`/`DROP
  INDEX`/`ROLLBACK` cycle keeps this test non-destructive) rather than by
  the planner's cost estimate alone.
  """

  import Ecto.Query

  alias Amanogawa.Atlas.Event
  alias Amanogawa.Repo

  @type envelope :: %{min_lon: float(), min_lat: float(), max_lon: float(), max_lat: float()}
  @type opts :: %{
          envelopes: [envelope(), ...],
          from: integer(),
          to: integer(),
          limit: pos_integer()
        }
  @type row :: %{
          qid: String.t(),
          label: String.t() | nil,
          year: integer(),
          precision: integer(),
          importance: integer(),
          geom: Geo.Point.t()
        }

  @doc """
  Lists events intersecting `opts.envelopes`, overlapping the
  `[opts.from, opts.to]` year window, ranked by importance, limited to
  `opts.limit` rows. Events without a geometry are excluded.

  Returns the minimal projection needed to build a GeoJSON feature: `qid`,
  a French-with-English-fallback `label`, `year`/`precision` (the begin
  date only: the map shows a punctual marker), `importance`, and `geom`.
  """
  @spec list_events(opts()) :: [row()]
  def list_events(%{envelopes: envelopes, from: from, to: to, limit: limit}) do
    Event
    |> where([e], not is_nil(e.geom))
    |> where(^bbox_condition(envelopes))
    |> where([e], e.begin_year <= ^to and coalesce(e.end_year, e.begin_year) >= ^from)
    |> order_by([e], desc: e.sitelink_count, asc: e.qid)
    |> limit(^limit)
    |> select([e], %{
      qid: e.qid,
      label: coalesce(e.label_fr, e.label_en),
      year: e.begin_year,
      precision: e.begin_precision,
      importance: e.sitelink_count,
      geom: e.geom
    })
    |> Repo.all()
  end

  defp bbox_condition(envelopes) do
    Enum.reduce(envelopes, dynamic(false), fn envelope, acc ->
      dynamic(
        [e],
        ^acc or
          fragment(
            "ST_Intersects(?, ST_MakeEnvelope(?, ?, ?, ?, 4326))",
            e.geom,
            ^envelope.min_lon,
            ^envelope.min_lat,
            ^envelope.max_lon,
            ^envelope.max_lat
          )
      )
    end)
  end
end
