import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :amanogawa, AmanogawaWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. Note `:force_ssl` is required to be set at compile-time.
#
# `/health` (issue #026) is excluded: kamal-proxy probes it directly over
# the private Docker network (plain HTTP, no `x-forwarded-proto` header),
# never through the public HTTPS edge it terminates TLS for itself.
# Without this exclusion, `Plug.SSL` would see what looks like a bare HTTP
# request and redirect the probe to `https://`, which kamal-proxy's own
# healthcheck client does not follow, permanently marking the container
# unhealthy.
config :amanogawa, AmanogawaWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

# The JSON formatter labels every timestamp as UTC
# (`Amanogawa.Logging.JSONFormatter.format_timestamp/1` appends `Z`): make
# Logger hand it UTC wall clock times so that label stays truthful
# regardless of the host's timezone.
config :logger, utc_log: true

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
